### ISSUE TITLE
Add RSEM

### ISSUE THREAD

**Issue by golharam** [common-workflow-library/bio-cwl-tools#114]
I didn't see RSEM available as a tool here.  Is RSEM available?

**Comment by mr-c** [comment]
Not yet, I see some at https://github.com/search?q=extension%3Acwl+cwlVersion+rsem that might work. Feel free to [contribute](https://github.com/common-workflow-library/bio-cwl-tools/blob/release/CONTRIBUTING.md) any that you find!
