### ISSUE TITLE
setup CI for syntax validation

### ISSUE THREAD

**Issue by mr-c** [common-workflow-library/bio-cwl-tools#2]

**Comment by michael-kotliar** [comment]
we use this travis configuration file to run our tests with the hardcoded version of cwltool on every commit to the repository
https://github.com/Barski-lab/workflows/blob/master/.travis.yml

**Comment by mr-c** [comment]
Done, no more direct pushes to the `release` branch, must have a PR that passes TravisCI; reviews are not yet required
