### ISSUE TITLE
STAR cwl is pointing to the hisat container

### ISSUE THREAD

**Issue by nsheff** [common-workflow-library/bio-cwl-tools#99]
https://github.com/common-workflow-library/bio-cwl-tools/blob/7836e20b78d052a75027d9ed14064517780e60ec/STAR/STAR-Align.cwl#L7

I *think* this is probably a mistake, but anyway, this tool doesn't seem to work as this container doesn't actually contain the STAR executable.

**Comment by mr-c** [comment]
Thank you @nsheff for catching this! Can you try out #100 to see if I picked a good container?
